/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TreeSelectImport } from './routes/treeSelect'
import { Route as SkillTreeImport } from './routes/skillTree'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const TreeSelectRoute = TreeSelectImport.update({
  path: '/treeSelect',
  getParentRoute: () => rootRoute,
} as any)

const SkillTreeRoute = SkillTreeImport.update({
  path: '/skillTree',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/skillTree': {
      preLoaderRoute: typeof SkillTreeImport
      parentRoute: typeof rootRoute
    }
    '/treeSelect': {
      preLoaderRoute: typeof TreeSelectImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  AboutRoute,
  SkillTreeRoute,
  TreeSelectRoute,
])

/* prettier-ignore-end */
