const v2DbList = [
  'ancillaries',
  'ancillary_to_effects',
  'character_skill_level_details',
  'character_skill_level_to_ancillaries_junctions',
  'character_skill_level_to_effects_junctions',
  'character_skill_node_links',
  'character_skill_node_sets',
  'character_skill_nodes_skill_locks',
  'character_skill_nodes',
  'character_skills',
  'character_skills_to_quest_ancillaries',
  'cultures_subcultures',
  'cultures',
  'effect_bonus_value_unit_ability_junctions',
  'effects',
  'faction_agent_permitted_subtypes',
  'factions',
  'special_ability_phase_attribute_effects',
  'special_ability_phase_stat_effects',
  'special_ability_phases',
  'special_ability_to_special_ability_phase_junctions',
  'unit_abilities_additional_ui_effects',
  'unit_abilities',
  'unit_abilities_to_additional_ui_effects_juncs',
  'unit_ability_types',
  'unit_attributes',
  'unit_special_abilities',
  'ui_unit_stats',
  'battle_vortexs',
  'projectile_bombardments',
  'projectiles',
  'projectiles_explosions',
  'special_ability_to_auto_deactivate_flags',
  'special_ability_to_invalid_target_flags',
  'special_ability_invalid_usage_flags',
  'unit_set_unit_ability_junctions',
  'effect_bonus_value_unit_set_unit_ability_junctions',
  'effect_bonus_value_military_force_ability_junctions',
  'army_special_abilities',
  'effect_bundles',
  'effect_bundles_to_effects_junctions',
  'ancillary_types',
  'agent_subtypes',
  'ancillary_info',
  'banners',
  'modifiable_unit_stats',
  'unit_stat_localisations',
  'campaign_effect_scopes',
  'main_units',
  'land_units',
  'battle_entities',
  'unit_shield_types',
  'unit_armour_types',
  'melee_weapons',
  'missile_weapons',
  'unit_attributes_groups',
  'unit_attributes_to_groups_junctions',
  'land_units_to_unit_abilites_junctions',
  'mounts',
  'effect_bonus_value_unit_attribute_junctions',
  'effect_bonus_value_unit_set_unit_attribute_junctions',
  'unit_set_unit_attribute_junctions',
  'effect_bonus_value_battle_context_unit_attribute_junctions',
  'battle_context_unit_attribute_junctions',
  'effect_bonus_value_special_ability_phase_record_junctions',
  'effect_bonus_value_unit_set_special_ability_phase_junctions',
  'unit_set_special_ability_phase_junctions',
  'battle_context_unit_ability_junctions',
  'effect_bonus_value_battle_context_unit_ability_junctions',

  // Techs
  'technologies',
  'technology_effects_junction',
  'technology_node_links',
  'technology_node_sets',
  'technology_nodes',
  'technology_nodes_to_ancillaries_junctions',
  'technology_required_building_levels_junctions',
  'technology_required_technology_junctions',
  'technology_script_lock_reasons',
  'technology_ui_groups',
  'technology_ui_groups_to_technology_nodes_junctions',
  'building_levels',
  'building_culture_variants',
] as const;

const v3DbList = [
  ...v2DbList,
  'character_ancillary_quest_ui_details',
  'character_skills_to_level_reached_criterias',
  'faction_starting_general_effects',
  'special_ability_spreadings',
  'campaign_character_art_sets',
  'character_skill_node_set_items',
  'trait_info',
  'trait_categories',
  'character_trait_levels',
  'character_traits',
  'trait_level_effects',
  'names',
  'start_pos_factions',
  'campaigns',
  'ancillaries_included_agent_subtypes',
  'ancillary_sets',
  'ancillary_set_ancillary_junctions',
  'ancillary_set_effect_junctions',
  '_kv_rules',
  'effect_bonus_value_agent_subtype_junctions',
  'unit_variants',
  'effect_bonus_value_ids_unit_sets',
  'unit_sets',
  'unit_set_to_unit_junctions',
  'effect_bonus_value_missile_weapon_junctions',
  'unit_missile_weapon_junctions',
  'effect_bonus_value_unit_list_junctions',
  'unit_lists',
  'unit_to_unit_list_junctions',
  'effect_bonus_value_unit_record_junctions',

  // Tech
  // Table empty as of TW3 6.0
  // 'technology_ui_group_links',
] as const;

// Also have to manually handle new AssKit tables in akData.ts
const v3AssKitList = ['start_pos_characters', 'start_pos_calendars', 'start_pos_character_traits'];

export { v2DbList, v3DbList, v3AssKitList };
